import { join, relative } from 'node:path';
import type { FrameworkConfig } from '@declarativejs/core/config';

/**
 * Rewrites a config specifier into an import path relative to
 * `src/generated/manifest.ts`. Bare package names pass through; local paths
 * (relative to the project root) are relativized and stripped of `.ts`.
 */
function toImportPath(spec: string, projectRoot: string): string {
	if (!spec.startsWith('.')) return spec;
	const manifestDir = join(projectRoot, 'src', 'generated');
	let rel = relative(manifestDir, join(projectRoot, spec)).replace(
		/\.ts$/,
		''
	);
	if (!rel.startsWith('.')) rel = `./${rel}`;
	return rel;
}

function callExpression(exportName: string, options?: Record<string, unknown>): string {
	const args = options !== undefined ? JSON.stringify(options) : '';
	return `${exportName}(${args})`;
}

/**
 * The pure codegen: turns a FrameworkConfig into the manifest source. This is
 * the ONLY file the generator writes; `index.ts` and `environment.ts` are never
 * touched. Deterministic — identical config yields byte-identical output, so
 * `dcl gen --check` can assert the manifest is in sync in CI.
 */
export function generateManifestSource(
	config: FrameworkConfig,
	projectRoot: string
): string {
	const lines: string[] = [
		'// AUTO-GENERATED by `dcl gen` from framework.config.ts — DO NOT EDIT.',
		'// Regenerate with `dcl gen`. Manual edits are overwritten.',
		"import { defineManifest, type ManifestEden } from '@declarativejs/core/app';",
		`import { createEnvironment } from '${toImportPath(config.environment, projectRoot)}';`,
	];

	const telemetryCalls: string[] = [];
	for (const [name, entry] of Object.entries(config.telemetry ?? {})) {
		if (!entry.enabled) continue;
		const exportName = entry.export ?? `${name}Module`;
		lines.push(
			`import { ${exportName} } from '${toImportPath(entry.package, projectRoot)}';`
		);
		telemetryCalls.push(callExpression(exportName, entry.options));
	}

	const moduleCalls: string[] = [];
	for (const [name, entry] of Object.entries(config.modules)) {
		const exportName = entry.export ?? `${name}Module`;
		lines.push(
			`import { ${exportName} } from '${toImportPath(entry.package, projectRoot)}';`
		);
		moduleCalls.push(callExpression(exportName, entry.options));
	}

	lines.push('', 'export const manifest = defineManifest({', '\tcreateEnvironment,');
	if (telemetryCalls.length > 0) {
		lines.push(`\ttelemetry: [${telemetryCalls.join(', ')}],`);
	}
	lines.push(
		`\tmodules: [${moduleCalls.join(', ')}] as const,`,
		'});',
		'',
		'export type AppEden = ManifestEden<typeof manifest.modules>;',
		''
	);

	return lines.join('\n');
}
